// src/shared/ui/Button/Button.tsx
import React from "react";
import cn from "classnames";
import "./index.scss";

interface IButton extends React.ButtonHTMLAttributes<HTMLButtonElement> {
    variant?: string;
    size?: string;
    fullwidth?: boolean;
    className?: string;
    children?: React.ReactNode;
}

const Button: React.FC<IButton> = ({
                                       variant = "primary",
                                       size = "sm",
                                       fullwidth,
                                       className,
                                       children,
                                       ...rest
                                   }) => {
    const buttonClasses = [
        "a-button",
        `a-button--${variant}`,
        `a-button--${size}`,
        fullwidth ? "a-button--fullwidth" : null,
    ];

    return (
        <button className={cn(className, buttonClasses.join(" "))} {...rest}>
            {children || "Добавить"}
        </button>
    );
};

export default Button;

// src/shared/ui/button/index.vue
<script lang="ts">
export default {
  name: 'v-button'
}
</script>

<template>
  <button
      class="a-button"
      :class="[
        `a-button--${props.type}`,
        `a-button--${props.size}`,
        {
          'a-button--with-icon': props.withIcon,
          'a-button--wide': props.wide,
          'a-button--fullwidth': props.fullWidth,
        },
    ]"
  >
    <slot>Добавить</slot>
  </button>

</template>

<script setup lang="ts">
interface Props {
  type?: string,
  size?: string,
  withIcon?: boolean,
  wide?: boolean,
  fullWidth?: boolean,
}

const props = withDefaults(defineProps<Props>(), {
  type: 'primary',
  size: 'sm',
  withIcon: false,
  wide: false,
  fullWidth: false
})
</script>

<style scoped src="./index.scss">

</style>
